### ISSUE TITLE
Old version of Data Input zip!

### ISSUE THREAD

**Issue by MikeModder** [RedSoloFox/Plailect-SD-Helper#2]
This program still appears to download data input v2, while v3 is the latest.

**Comment by RedSoloFox** [comment]
It probably does. It was created before otpless was released and It hasn't been updated since. I may update it a bit within the next few days or I may rewrite it in c++ which may take a bit. Currently you might have to change the URL for the data input to the v3 for now as it *should* still work.

**Comment by RedSoloFox** [comment]
data input v3 is not available via gdrive. Updated with java https://github.com/RedSoloFox/A9LH-SD-Helper-J , dont use this as its outdated.
